//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AskNLearnEntities : DbContext
    {
        public AskNLearnEntities()
            : base("name=AskNLearnEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Comment> Comments { get; set; }
        public DbSet<Cours> Courses { get; set; }
        public DbSet<Document> Documents { get; set; }
        public DbSet<EnrolledUser> EnrolledUsers { get; set; }
        public DbSet<Mark> Marks { get; set; }
        public DbSet<Post> Posts { get; set; }
        public DbSet<Quize> Quizes { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UsersInfo> UsersInfoes { get; set; }
    }
}
