//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int did { get; set; }
        public int coid { get; set; }
        public string imageTitle { get; set; }
        public string image { get; set; }
        public string videoTitle { get; set; }
        public string videoLink { get; set; }
        public string docTitle { get; set; }
        public string docs { get; set; }
    
        public virtual Cours Cours { get; set; }
    }
}
