//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mark
    {
        public int mid { get; set; }
        public int eid { get; set; }
        public double marks { get; set; }
        public System.DateTime detaTime { get; set; }
        public int quizId { get; set; }
    
        public virtual Quize Quize { get; set; }
        public virtual Quize Quize1 { get; set; }
    }
}
