//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quize
    {
        public Quize()
        {
            this.Marks = new HashSet<Mark>();
            this.Marks1 = new HashSet<Mark>();
        }
    
        public int quizId { get; set; }
        public int coid { get; set; }
        public string quizTitle { get; set; }
        public string questionLink { get; set; }
        public string totalMarks { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual ICollection<Mark> Marks { get; set; }
        public virtual ICollection<Mark> Marks1 { get; set; }
    }
}
