//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersInfo
    {
        public int u_info_id { get; set; }
        public int uid { get; set; }
        public string eduInfo { get; set; }
        public string currentPosition { get; set; }
        public int reputation { get; set; }
    
        public virtual User User { get; set; }
    }
}
